metadata:
  labels:
    app: @project.artifactId@
spec:
  replicas: 1
  template:
    spec:
      containers:
        - env:
            - name: SPRING_PROFILES_ACTIVE
              value: 'default'
            - name: JAVA_MAX_MEM_RATIO
              value: '0'
            - name: JAVA_TOOL_OPTIONS
              value: >-
                -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
                -Djava.net.preferIPv4Stack=true
          name: msadp-d-domain-deposit-accounts-movements
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9779
              name: prometheus
              protocol: TCP
            - containerPort: 8778
              name: jolokia
              protocol: TCP
            - containerPort: 8181
              name: actuator
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 240
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health
              port: 8181
              scheme: HTTP
            initialDelaySeconds: 240
            periodSeconds: 15
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
          - name: @project.artifactId@-config
            mountPath: /deployments/config
      volumes:
        - name: @project.artifactId@-config
          configMap:
            name: @project.artifactId@